class Constants {
  Constants._();

  static const List<String> featuredCompounds = [
    'Acetic Acid',
    'Acetone',
    'Alanine',
    'Ammonia',
    'Ascorbic Acid',
    'Aspirin',
    'Benzene',
    'Calcium Carbonate',
    'Caffeine',
    'Cholesterol',
    'Citric Acid',
    'Creatine',
    'Dopamine',
    'Ethanol',
    'Formaldehyde',
    'Fructose',
    'Glucose',
    'Glycine',
    'Hydrogen Peroxide',
    'Ibuprofen',
    'Lactose',
    'Methanol',
    'Nitric Acid',
    'Paracetamol',
    'Potassium Chloride',
    'Sodium Chloride',
    'Sucrose',
    'Sulfuric Acid',
    'Toluene',
    'Urea',
  ];
}
